apiVersion: v1
kind: Service
metadata:
  namespace: myproject
  name: my-service-name
spec:
  selector:
    component: my-service-name
  clusterIP: None
  ports:
  - name: hz-port-name
    port: 5701
    protocol: TCP
