spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 10
      intervalSeconds: 20
      timeoutSeconds: 600
      maxUnavailable: 1
      maxSurge: 1
  template:
    spec:
      containers:
        - name: vertx
          env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: JAVA_ARGS
              value: '-Dvertx.cacheDirBase=/tmp -Djava.net.preferIPv4Stack=true -cluster'
          terminationGracePeriodSeconds: 90
